#! /usr/bin/python

import os
import sys


# ################################layer2 functions##############################

def generateDeployEnglish():
    os.system('hexo clean')
    os.system('hexo d -g')


def generateEnglish():
    os.system('hexo clean')
    os.system('hexo g')


def deployEnglish():
    os.system('hexo d')


def serverEnglish():
    os.system('xdg-open http://localhost:4000')
    os.system('hexo s')


def generateDeployChinese():
    os.system('hexo clean --config _config.yml,_config.zh-CN.yml')
    os.system('hexo d -g --config _config.yml,_config.zh-CN.yml')


def generateChinese():
    os.system('hexo clean --config _config.yml,_config.zh-CN.yml')
    os.system('hexo g --config _config.yml,_config.zh-CN.yml')


def deployChinese():
    os.system('hexo d --config _config.yml,_config.zh-CN.yml')


def serverChinese():
    os.system('xdg-open http://localhost:4000')
    os.system('hexo server --config _config.yml,_config.zh-CN.yml')

# ################################layer1 functions##############################


def generateDeployAll():
    os.system('hexo clean')
    os.system('hexo d -g')
    os.system('hexo clean --config _config.yml,_config.zh-CN.yml')
    os.system('hexo d -g --config _config.yml,_config.zh-CN.yml')


def english():
    layer2 = {
        'default': generateDeployEnglish,
        'g': generateEnglish,
        'd': deployEnglish,
        's': serverEnglish
    }
    child = layer2[sys.argv[2] if len(sys.argv) > 2 else 'default']
    child()


def chinese():
    layer2 = {
        'default': generateDeployChinese,
        'g': generateChinese,
        'd': deployChinese,
        's': serverChinese
    }
    child = layer2[sys.argv[2] if len(sys.argv) > 2 else 'default']
    child()


def newEnglish():
    os.system('hexo new' + ' "' + sys.argv[2] + '"')


def newChinese():
    os.system('hexo new' + ' "' +
              sys.argv[2] + '"' + ' --config _config.yml,_config.zh-CN.yml')


def newAll():
    os.system('hexo new' + ' "' + sys.argv[2])
    os.system('hexo new' + ' "' +
              sys.argv[3] + ' --config _config.yml,_config.zh-CN.yml')
    # os.system('python\python.exe multi-language.py' +
            #   sys.argv[2] + sys.argv[3])


def clean():
    os.system('hexo clean')


layer1 = {
    'default': generateDeployAll,
    'e': english,
    'c': chinese,
    'ne': newEnglish,
    'nc': newChinese,
    'na': newAll,
    'clean': clean
}
# ##############################################################################

# add hexo to PATH
os.environ['PATH'] = os.path.abspath(
    '.') + '/node_modules/hexo-cli/bin/' + ':' + os.environ['PATH']

# the main process
main = layer1[sys.argv[1] if len(sys.argv) > 1 else 'default']
main()
